local bytes = require("@bytes")

testing:test("Bytes.split_off", function(t)
    local b = bytes.Bytes.new("hello world")
    local other = b:split_off(6)
    t.assert_eq(tostring(b), "hello ")
    t.assert_eq(tostring(other), "world")
end)

testing:test("Bytes.split_to", function(t)
    local b = bytes.Bytes.new("hello world")
    local other = b:split_to(5)
    t.assert_eq(tostring(b), " world")
    t.assert_eq(tostring(other), "hello")
end)

testing:test("Bytes.clear", function(t)
    local b = bytes.Bytes.new("hello")
    b:clear()
    t.assert_eq(b:len(), 0)
    t.assert_eq(b:is_empty(), true)
end)

testing:test("Bytes.truncate", function(t)
    local b = bytes.Bytes.new("hello")
    b:truncate(2)
    t.assert_eq(tostring(b), "he")
    t.assert_eq(b:len(), 2)
end)
